### ISSUE TITLE
ClojureScript string requires (npm) cause exception

### ISSUE THREAD

**Issue by pesterhazy** [clojure-lsp/clojure-lsp#133]
When using a [string require](https://clojurescript.org/news/2017-07-12-clojurescript-is-not-an-island-integrating-node-modules#_a_practical_example) in CLJS, I get an exception. For example, [this line](https://github.com/pesterhazy/cljs-spa-example/blob/master/src/cljs_spa/router.cljs#L6) gives me:

```
WARN  clojure-lsp.crawler: Cannot parse:  file:///Users/user/prg/cljs-spa-example/src/cljs_spa/router.cljs java.lang.String cannot be cast to clojure.lang.Named
java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.Named
	at clojure.core$namespace.invokeStatic(core.clj:1597)
	at clojure.core$namespace.invoke(core.clj:1597)
	at clojure_lsp.crawler$diagnose_unused_aliases$fn__12142.invoke(crawler.clj:141)
	at clojure.core$map$fn__5866.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$reduce1.invokeStatic(core.clj:930)
	at clojure.core$set.invokeStatic(core.clj:4113)
	at clojure.core$set.invoke(core.clj:4105)
	at clojure_lsp.crawler$diagnose_unused_aliases.invokeStatic(crawler.clj:139)
	at clojure_lsp.crawler$diagnose_unused_aliases.invoke(crawler.clj:138)
	at clojure_lsp.crawler$diagnose_unused.invokeStatic(crawler.clj:159)
	at clojure_lsp.crawler$diagnose_unused.invoke(crawler.clj:150)
	at clojure_lsp.crawler$find_diagnostics.invokeStatic(crawler.clj:164)
	at clojure_lsp.crawler$find_diagnostics.invoke(crawler.clj:162)
	at clojure_lsp.crawler$safe_find_references.invokeStatic(crawler.clj:183)
	at clojure_lsp.crawler$safe_find_references.invoke(crawler.clj:170)
	at clojure_lsp.crawler$safe_find_references.invokeStatic(crawler.clj:172)
	at clojure_lsp.crawler$safe_find_references.invoke(crawler.clj:170)
	at clojure_lsp.handlers$did_change.invokeStatic(handlers.clj:286)
	at clojure_lsp.handlers$did_change.invoke(handlers.clj:282)
	at clojure.lang.Var.invoke(Var.java:393)
	at clojure_lsp.main.LSPTextDocumentService.didChange(main.clj:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

String requires are a relatively new feature of CLJS, uses when importing modules from NPM.

PS, clojure-lsp is a fantastic project! I admire how far you've come with it already.

**Comment by ericdallo** [comment]
Thank you @pesterhazy!
This already works as expected after we merged #261 :)
