### ISSUE TITLE
dev flake not working after make -> bb migration

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#1373]
After we replaced all makefile tasks with babashka, the flakes.nix derivation stopped working:

repro on project root:
```
nix shell
```

**Comment by ericdallo** [comment]
I tried replacing the `make cli-jar-for-native` with `${pkgs.babashka}/bin/bb cli-jar-for-native` [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/flake.nix#L31), but it seems babashka is trying to download something from internet witch is not possible during nix builds:

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/izdx6kyp2dx1mmyimcprnq40z3mlmr2g-7kc8nzyy5nmg27idd4rw7ajbx2gih4d2-source
source root is 7kc8nzyy5nmg27idd4rw7ajbx2gih4d2-source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
WARNING: this project requires babashka 0.8.156 or newer, but you have: 0.8.2
Could not find /build/.deps.clj/1.11.1.1113/ClojureTools/clojure-tools-1.11.1.1113.jar
Downloading tools jar from https://download.clojure.org/install/clojure-tools-1.11.1.1113.zip to /build/.deps.clj/1.11.1.1113/ClojureTools
Exception in thread "main" java.net.UnknownHostException: download.clojure.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:609)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
        at borkdude.deps$download.invokeStatic(deps.clj:229)
        at borkdude.deps$clojure_tools_jar_download.invokeStatic(deps.clj:255)
        at borkdude.deps$_main$fn__10240.invoke(deps.clj:467)
        at borkdude.deps$_main.invokeStatic(deps.clj:467)
        at borkdude.deps$_main.doInvoke(deps.clj:425)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.impl.deps$add_deps$fn__30495$fn__30496.invoke(deps.clj:92)
        at babashka.impl.deps$add_deps$fn__30495.invoke(deps.clj:92)
        at babashka.impl.deps$add_deps.invokeStatic(deps.clj:92)
        at babashka.main$exec.invokeStatic(main.clj:766)
        at babashka.main$main.invokeStatic(main.clj:1021)
        at babashka.main$main.doInvoke(main.clj:996)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.main$_main.invokeStatic(main.clj:1054)
        at babashka.main$_main.doInvoke(main.clj:1046)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at babashka.main.main(Unknown Source)
```

Any thoughts @jlesquembre?

**Comment by jlesquembre** [comment]
clj-nix doesn't look for the babashka dependencies (in `bb.edn`), and those deps are not added to the lock file. 

Also, looks like babashka expects a specific `clojure-tools` version, in the `~/.deps.clj` directory. Maybe we could fix that directly in nixpkgs. 

I'll look into this, but I'm not sure when.

**Comment by ericdallo** [comment]
Thank you!
