### ISSUE TITLE
JetBrains Exception when attemping to refactor/rename a file

### ISSUE THREAD

**Issue by codewriter3000** [clojure-lsp/clojure-lsp#1776]
**Describe the bug**
I get an exception leading me to this tool every time I attempt to rename a file.

**To Reproduce**
1. Click on a file.
2. Either hit Shift + F6 (the shortcut for refactoring), or right-click on it to bring up the tooltip to rename it.

**Expected behavior**
A dialog for the new file name.

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
n/a
</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
java.lang.StackOverflowError
	at com.intellij.openapi.util.registry.Registry.getInstance(Registry.java:180)
	at com.intellij.openapi.util.registry.Registry.get(Registry.java:45)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:58)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.reportValueProvidedByRulesUsage(PreCachedDataContext.java:250)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getDataInner(PreCachedDataContext.java:221)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext$InjectedDataContext.lambda$getDataInner$0(PreCachedDataContext.java:387)
	at com.intellij.openapi.actionSystem.InjectedDataKeys.getInjectedData(InjectedDataKeys.java:57)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext$InjectedDataContext.getDataInner(PreCachedDataContext.java:387)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getData(PreCachedDataContext.java:174)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:57)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invokeStatic(rename.clj:48)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invoke(rename.clj:45)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invokeStatic(rename.clj:48)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invoke(rename.clj:45)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invokeStatic(rename.clj:48)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invoke(rename.clj:45)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invokeStatic(rename.clj:48)
...
(this goes on for a pretty long time)
</pre>
</details>

**User details (please complete the following information):**
 - OS: Windows 11
 - Editor: PyCharm 2023.3
 - Version: 1.14.9

**Comment by ericdallo** [comment]
THanks for the report @codewriter3000, This should be a issue on https://github.com/clojure-lsp/clojure-lsp-intellij, would you mind opening it there?
