### ISSUE TITLE
Exception thrown when clj-kondo diagnostic has severity `:ignore`

### ISSUE THREAD

**Issue by NoahTheDuke** [clojure-lsp/clojure-lsp#1882]
https://github.com/clojure-lsp/clojure-lsp/blob/6032da281da9da0139e9bb469e8b694de0118725/lib/src/clojure_lsp/feature/diagnostics.clj#L115-L118

traceback:

```
2024-09-12T01:29:18.969Z  ERROR [clojure-lsp.server:55] - Error receiving message: Internal error (-32603)
{:method "textDocument/didOpen"}
 com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine     PlatformThreads.java:  872
 com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine     PlatformThreads.java:  896
                                          java.lang.Thread.run              Thread.java: 1583
                                      java.lang.Thread.runWith              Thread.java: 1596
            java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  642
             java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1144
                                                           ...
                             clojure.core.async/thread-call/fn                async.clj:  486
                                 lsp4clj.server/thread-loop/fn               server.clj:  122
                                  lsp4clj.server.ChanServer/fn               server.clj:  261
                lsp4clj.server.ChanServer/receive-notification               server.clj:  403
                                                           ...
                                         clojure-lsp.server/fn               server.clj:  223
                                 clojure-lsp.handlers/did-open             handlers.clj:  201
                  clojure-lsp.feature.file-management/did-open      file_management.clj:   48
          clojure-lsp.feature.diagnostics/publish-diagnostics!          diagnostics.clj:  204
            clojure-lsp.feature.diagnostics/diagnostics-of-uri          diagnostics.clj:  197
              clojure-lsp.feature.diagnostics/find-diagnostics          diagnostics.clj:  184
   clojure-lsp.feature.diagnostics/kondo-findings->diagnostics          diagnostics.clj:  146
                                             clojure.core/mapv                 core.clj: 6971
                                           clojure.core/reduce                 core.clj: 6887
                                   clojure.core.protocols/fn/G            protocols.clj:   13
                                     clojure.core.protocols/fn            protocols.clj:   75
                             clojure.core.protocols/seq-reduce            protocols.clj:   31
                                   clojure.core.protocols/fn/G            protocols.clj:   19
                                     clojure.core.protocols/fn            protocols.clj:  136
                                                           ...
                                          clojure.core/mapv/fn                 core.clj: 6980
clojure-lsp.feature.diagnostics/kondo-findings->diagnostics/fn          diagnostics.clj:  146
     clojure-lsp.feature.diagnostics/kondo-finding->diagnostic          diagnostics.clj:  115
java.lang.IllegalArgumentException: No matching clause: :ignore
```

It seems to be caused by this code:

```clojure
(def extra-config-dev
  "Add dev-time configuration overrides here, such as `:hide-future-posts? false`"
  {
   #_#_:postprocess-article-html-fn #'postprocess-article
   })
```

If I delete the line, clojure-lsp works. if I add it back in, it throws the exception above.

**Comment by NoahTheDuke** [comment]
And from the command line:

```
$ clojure-lsp diagnostics
[ 99%] Project analyzed            Finding diagnostics...
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No matching clause: :ignore
	at java.base@21.0.4/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base@21.0.4/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at clojure.core$deref_future.invokeStatic(core.clj:2317)
	at clojure.core$future_call$reify__8544.deref(core.clj:7042)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at clojure.core$map$fn__5935.invoke(core.clj:2772)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:58)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6887)
	at clojure.core$reduce.invoke(core.clj:6869)
	at clojure_lsp.internal_api$diagnostics_STAR_.invokeStatic(internal_api.clj:346)
	at clojure_lsp.internal_api$diagnostics_STAR_.invoke(internal_api.clj:336)
	at clojure_lsp.internal_api$diagnostics.invokeStatic(internal_api.clj:484)
	at clojure_lsp.internal_api$diagnostics.invoke(internal_api.clj:483)
	at clojure_lsp.main$handle_action_BANG_.invokeStatic(main.clj:159)
	at clojure_lsp.main$handle_action_BANG_.invoke(main.clj:150)
	at clojure_lsp.main$run_BANG_.invokeStatic(main.clj:180)
	at clojure_lsp.main$run_BANG_.doInvoke(main.clj:173)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at clojure_lsp.main$main.invokeStatic(main.clj:183)
	at clojure_lsp.main$main.doInvoke(main.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at clojure_lsp.main$_main.invokeStatic(main.clj:208)
	at clojure_lsp.main$_main.doInvoke(main.clj:206)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure_lsp.main.main(Unknown Source)
	at java.base@21.0.4/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.IllegalArgumentException: No matching clause: :ignore
	at clojure_lsp.feature.diagnostics$kondo_finding__GT_diagnostic.invokeStatic(diagnostics.clj:115)
	at clojure_lsp.feature.diagnostics$kondo_finding__GT_diagnostic.invoke(diagnostics.clj:92)
	at clojure_lsp.feature.diagnostics$kondo_findings__GT_diagnostics$fn__17176.invoke(diagnostics.clj:146)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6980)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
	at clojure.core.protocols$fn__8244.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__8244.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6887)
	at clojure.core$mapv.invokeStatic(core.clj:6971)
	at clojure.core$mapv.invoke(core.clj:6971)
	at clojure_lsp.feature.diagnostics$kondo_findings__GT_diagnostics.invokeStatic(diagnostics.clj:146)
	at clojure_lsp.feature.diagnostics$kondo_findings__GT_diagnostics.invoke(diagnostics.clj:137)
	at clojure_lsp.feature.diagnostics$find_diagnostics.invokeStatic(diagnostics.clj:184)
	at clojure_lsp.feature.diagnostics$find_diagnostics.invoke(diagnostics.clj:177)
	at clojure_lsp.internal_api$diagnostics_STAR_$fn__37393.invoke(internal_api.clj:344)
	at clojure.core$pmap$fn__8552$fn__8553.invoke(core.clj:7090)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base@21.0.4/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
^C
```

**Comment by NoahTheDuke** [comment]
I forgot:

OS: Mac OSX
Version:
```
$ clojure-lsp --version
clojure-lsp 2024.08.05-18.16.00
clj-kondo 2024.08.01
```

**Comment by NoahTheDuke** [comment]
On further inspection, I believe this is actually coming from .clj-kondo config with `{:linters {:clojure-lsp/unused-public-var {:level :ignore}}}`.

**Comment by NoahTheDuke** [comment]
Ope, it's supposed to be `:level :off`. That's my bad haha.
