### ISSUE TITLE
Can not start on termux

### ISSUE THREAD

**Issue by lost22git** [clojure-lsp/clojure-lsp#1922]
I get this error when starting lsp. It seem not to create tmp file on my termux which tmp dir pointer to  /data/data/com.termux/files/usr/tmp

```
Exception in thread "main" java.io.IOException: No such file or directory
	at java.base@21/java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.base@21/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
	at java.base@21/java.io.File.createTempFile(File.java:2184)
	at java.base@21/java.io.File.createTempFile(File.java:2230)
	at clojure_lsp.server.TimbreLogger.setup(server.clj:72)
	at clojure_lsp.server$start_server_BANG_.invokeStatic(server.clj:616)
	at clojure_lsp.server$start_server_BANG_.invoke(server.clj:609)
	at clojure_lsp.server$run_lsp_io_server_BANG_.invokeStatic(server.clj:639)
	at clojure_lsp.server$run_lsp_io_server_BANG_.invoke(server.clj:633)
	at clojure_lsp.main$handle_action_BANG_.invokeStatic(main.clj:153)
	at clojure_lsp.main$handle_action_BANG_.invoke(main.clj:150)
	at clojure_lsp.main$run_BANG_.invokeStatic(main.clj:180)
	at clojure_lsp.main$run_BANG_.doInvoke(main.clj:173)
	at clojure.lang.RestFn.applyTo(RestFn.java:140)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at clojure_lsp.main$main.invokeStatic(main.clj:183)
	at clojure_lsp.main$main.doInvoke(main.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:140)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at clojure_lsp.main$_main.invokeStatic(main.clj:208)
	at clojure_lsp.main$_main.doInvoke(main.clj:206)
	at clojure.lang.RestFn.applyTo(RestFn.java:140)
	at clojure_lsp.main.main(Unknown Source)
	at java.base@21/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

```

I try to add `-Djava.io.tmpdir=mytmpdir` but still not works.

**Comment by ericdallo** [comment]
Yeah, it's the temp file indeed, but I never saw that problem and besides your try I have no idea how to fix it 🤔

**Comment by lost22git** [comment]
https://github.com/oracle/graal/issues/7731
