### ISSUE TITLE
Unused shadow-cljs default import throws Exceptions

### ISSUE THREAD

**Issue by emmanuj** [clojure-lsp/clojure-lsp#193]
When using shadow-cljs with doom-emacs in Clojure mode, something like the following require if unused throws a null pointer exception in the lsp logs and causes the lsp-mode to stop working in Emacs.

`(:require ["@material-ui/core/Button" :default Button])`

Here's the output: 

```
DEBUG clojure-lsp.main: :didChange 21 ([:codeAction #{8327184590012}])
ERROR clojure-lsp.interop: :clojure-lsp.interop/publish-diagnostics-params {:uri file:///(<path-omitted)>/game.cljs, :diagnostics ()}
java.lang.NullPointerException
        at clojure.lang.Numbers.ops(Numbers.java:1068)
        at clojure.lang.Numbers.dec(Numbers.java:145)
        at clojure_lsp.shared$__GT_range.invokeStatic(shared.clj:17)
        at clojure_lsp.shared$__GT_range.invoke(shared.clj:16)
        at clojure_lsp.crawler$kondo_finding__GT_diagnostic.invokeStatic(crawler.clj:100)
        at clojure_lsp.crawler$kondo_finding__GT_diagnostic.invoke(crawler.clj:96)
        at clojure.core$map$fn__5866.invoke(core.clj:2753)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$concat$cat__5495$fn__5496.invoke(core.clj:734)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:58)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$seq__5402.invoke(core.clj:137)
        at clojure.spec.alpha$every_impl$reify__2254.conform_STAR_(alpha.clj:1291)
        at clojure.spec.alpha$conform.invokeStatic(alpha.clj:164)
        at clojure.spec.alpha$conform.invoke(alpha.clj:160)
        at clojure.spec.alpha$map_spec_impl$reify__1997.conform_STAR_(alpha.clj:837)
        at clojure.spec.alpha$and_spec_impl$fn__2177.invoke(alpha.clj:1154)
        at clojure.spec.alpha$and_spec_impl$reify__2183.conform_STAR_(alpha.clj:1183)
        at clojure.spec.alpha$conform.invokeStatic(alpha.clj:164)
        at clojure.spec.alpha$conform.invoke(alpha.clj:160)
        at clojure_lsp.interop$conform_or_log.invokeStatic(interop.clj:333)
        at clojure_lsp.interop$conform_or_log.invoke(interop.clj:330)
        at clojure_lsp.main$run$fn__26596$state_machine__18014__auto____26603$fn__26605.invoke(main.clj:455)
        at clojure_lsp.main$run$fn__26596$state_machine__18014__auto____26603.invoke(main.clj:455)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__18032.invoke(ioc_macros.clj:991)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__13497$fn__13498.invoke(channels.clj:95)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__13400$fn__13401.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

I have the latest version of `clojure-lsp` as of this posting.

**Comment by ericdallo** [comment]
@emmanuj could you try again with latest version?
With had a huge refactor which now rely on clj-kondo for parse/analysis that should work

**Comment by ericdallo** [comment]
Feel free to reopen if not fixed
