### ISSUE TITLE
clojure-lsp.crawler java.lang.ClassCastException

### ISSUE THREAD

**Issue by FongHou** [clojure-lsp/clojure-lsp#242]
clojure-lsp.crawler still fails to parse some source files. This ClassCastException is one of causes.

Below stacktrace points to this [line](https://github.com/clojure-lsp/clojure-lsp/blob/3a34e84d600a6830601348a7f2bea86a502bcfbf/src/clojure_lsp/parser.clj#L240) in parser.clj.  I don't understand the code, but I think the exception is due to (keyword , ) second argument only take String (not Symbol nor Keyword). However (cond->> ...) under certain condition (ok-ns? is false) thread through a Symbol to that.

Strangly, 1-arity (keyword ) works fine with symbol. Here is a demo.

```
cljdata.core=> (keyword 'bar)
:bar
cljdata.core=> (keyword (namespace :foo/bar) 'bar)
Execution error (ClassCastException) at cljdata.core/eval42828 (form-init17274768234266617442.clj:1).
class clojure.lang.Symbol cannot be cast to class java.lang.String (clojure.lang.Symbol is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

cljdata.core=> (keyword (namespace :foo/bar) (name 'bar))
:foo/bar
cljdata.core=>
``` 

```
INFO  clojure-lsp.crawler: Crawling jar /home/haskeller/.m2/repository/org/clojure/clojure/1.10.2-rc1/clojure-1.10.2-rc1.jar
WARN  clojure-lsp.parser: bindings clojure.lang.Symbol cannot be cast to java.lang.String [{:s/keys [problems value args ret fn failure spec]} explain-data caller (or (:clojure.spec.test.alpha/caller explain-data) (:orchestra.spec.test/caller explain-data)) form (if (not= :instrument failure) value (cond (contains? explain-data :s/ret) ret (contains? explain-data :s/args) args (contains? explain-data :s/fn) fn :else (throw (ex-info Invalid explain-data {:explain-data explain-data})))) problems' (map (comp (partial adjust-in form) (partial adjust-path failure) (partial add-spec spec) (partial fix-via spec) (fn* [p1__41356#] (assoc p1__41356# :expound/form form)) (fn* [p1__41358#] (assoc p1__41358# :expound.spec.problem/type (ptype failure p1__41358# false)))) problems)] (let [{:s/keys [problems value args ret fn failure spec]} explain-data caller (or (:clojure.spec.test.alpha/caller explain-data) (:orchestra.spec.test/caller explain-data)) form (if (not= :instrument failure) value (cond (contains? explain-data :s/ret) ret (contains? explain-data :s/args) args (contains? explain-data :s/fn) fn :else (throw (ex-info Invalid explain-data {:explain-data explain-data})))) problems' (map (comp (partial adjust-in form) (partial adjust-path failure) (partial add-spec spec) (partial fix-via spec) (fn* [p1__41361#] (assoc p1__41361# :expound/form form)) (fn* [p1__41363#] (assoc p1__41363# :expound.spec.problem/type (ptype failure p1__41363# false)))) problems)] (-> explain-data (assoc :expound/form form :expound/caller caller :expound/problems problems')))
WARN  clojure-lsp.parser: Cannot parse zipfile:///home/haskeller/.m2/repository/expound/expound/0.8.7/expound-0.8.7.jar::expound/problems.cljc
 clojure.lang.Symbol cannot be cast to java.lang.String
 (let [{::s/keys [problems value args ret fn failure spec]} explain-data
        caller (or (:clojure.spec.test.alpha/caller explain-data) (:orchestra.spec.test/caller explain-data))
        form (if (not= :instrument failure)
               value
               (cond
                 (contains? explain-data ::s/ret) ret
                 (contains? explain-data ::s/args) args
                 (contains? explain-data ::s/fn) fn
                 :else (throw (ex-info "Invalid explain-data" {:explain-data explain-data}))))
        problems' (map (comp (partial adjust-in form)
                             (partial adjust-path failure)
                             (partial add-spec spec)
                             (partial fix-via spec)
                             #(assoc % :expound/form form)
                             #(assoc % :expound.spec.problem/type (ptype failure % false)))
                       problems)]

    (-> explain-data
        (assoc :expound/form form
               :expound/caller caller
               :expound/problems problems')))
java.lang.ClassCastException: clojure.lang.Symbol cannot be cast to java.lang.String
        at clojure.core$keyword.invokeStatic(core.clj:614)
        at clojure.core$keyword.invoke(core.clj:614)
        at clojure_lsp.parser$destructure_keys.invokeStatic(parser.clj:240)
        at clojure_lsp.parser$destructure_keys.invoke(parser.clj:217)
        at clojure_lsp.parser$destructure_map.invokeStatic(parser.clj:268)
        at clojure_lsp.parser$destructure_map.invoke(parser.clj:259)
        at clojure_lsp.parser$parse_destructuring.invokeStatic(parser.clj:336)
        at clojure_lsp.parser$parse_destructuring.invoke(parser.clj:308)
        at clojure_lsp.parser$parse_bindings.invokeStatic(parser.clj:373)
        at clojure_lsp.parser$parse_bindings.invoke(parser.clj:346)
        at clojure_lsp.parser$handle_let.invokeStatic(parser.clj:551)
        at clojure_lsp.parser$handle_let.invoke(parser.clj:548)
        at clojure_lsp.parser$handle_sexpr.invokeStatic(parser.clj:1048)
        at clojure_lsp.parser$handle_sexpr.invoke(parser.clj:1027)
        at clojure_lsp.parser$find_usages_STAR_.invokeStatic(parser.clj:1084)
        at clojure_lsp.parser$find_usages_STAR_.invoke(parser.clj:1057)
```

**Comment by ericdallo** [comment]
@FongHou Thanks for the report! This should be fixed on latest release, I hope when we finish #176 we could remove all that parser logic and avoid these kinds of issues :)
