### ISSUE TITLE
Null pointer exception on Windows during initialization with version 2021.01.26-22.35.27

### ISSUE THREAD

**Issue by bpringe** [clojure-lsp/clojure-lsp#282]
On Windows during initialization (after the request was sent from client but before a response is received), an error occurs and no response is returned. I see this in the trace logs:

```
Jan 20, 2021 11:37:14 AM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: Cannot invoke "java.util.concurrent.CompletableFuture.thenAccept(java.util.function.Consumer)" because "future" is null
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletableFuture.thenAccept(java.util.function.Consumer)" because "future" is null
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

And this is in `/tmp/clojure-lsp.out`:

```
2021/01/20 11:37:14 8268 INFO  clojure-lsp.crawler Analyzing 10 paths with clj-kondo with batch size of  1 ...
2021/01/20 11:37:14 8268 ERROR clojure-lsp.main #error {
 :cause The filename, directory name, or volume label syntax is incorrect
 :via
 [{:type java.io.IOException
   :message The filename, directory name, or volume label syntax is incorrect
   :at [java.io.WinNTFileSystem canonicalize0 WinNTFileSystem.java -2]}]
 :trace
 [[java.io.WinNTFileSystem canonicalize0 WinNTFileSystem.java -2]
  [java.io.WinNTFileSystem canonicalize WinNTFileSystem.java 415]
  [java.io.File getCanonicalPath File.java 621]
  [clj_kondo.impl.core$process_file invokeStatic core.clj 360]
  [clj_kondo.impl.core$process_file invoke core.clj 306]
  [clj_kondo.impl.core$process_files$fn__15553 invoke core.clj 372]
  [clojure.core$run_BANG_$fn__8790 invoke core.clj 7715]
  [clojure.lang.PersistentVector reduce PersistentVector.java 343]
  [clojure.core$reduce invokeStatic core.clj 6827]
  [clojure.core$run_BANG_ invokeStatic core.clj 7710]
  [clojure.core$run_BANG_ invoke core.clj 7710]
  [clj_kondo.impl.core$process_files invokeStatic core.clj 372]
  [clj_kondo.impl.core$process_files invoke core.clj 367]
  [clj_kondo.core$run_BANG_ invokeStatic core.clj 136]
  [clj_kondo.core$run_BANG_ invoke core.clj 51]
  [clojure_lsp.crawler$run_kondo_on_paths_BANG_ invokeStatic crawler.clj 93]
  [clojure_lsp.crawler$run_kondo_on_paths_BANG_ invoke crawler.clj 92]
  [clojure_lsp.crawler$run_kondo_on_paths_batch_BANG_ invokeStatic crawler.clj 105]
  [clojure_lsp.crawler$run_kondo_on_paths_batch_BANG_ invoke crawler.clj 96]
  [clojure_lsp.crawler$analyze_paths invokeStatic crawler.clj 154]
  [clojure_lsp.crawler$analyze_paths invoke crawler.clj 151]
  [clojure_lsp.crawler$analyze_classpath invokeStatic crawler.clj 183]
  [clojure_lsp.crawler$analyze_classpath invoke crawler.clj 167]
  [clojure_lsp.crawler$analyze_project invokeStatic crawler.clj 190]
  [clojure_lsp.crawler$analyze_project invoke crawler.clj 186]
  [clojure_lsp.crawler$initialize_project invokeStatic crawler.clj 226]
  [clojure_lsp.crawler$initialize_project invoke crawler.clj 215]
  [clojure_lsp.handlers$initialize invokeStatic handlers.clj 105]
  [clojure_lsp.handlers$initialize invoke handlers.clj 103]
  [clojure.lang.Var invoke Var.java 393]
  [clojure_lsp.main$fn__30484$fn__30485 invoke main.clj 308]
  [clojure_lsp.main.proxy$clojure_lsp.ClojureExtensions$LanguageServer$c8d5825a initialize nil -1]
  [jdk.internal.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
  [jdk.internal.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 64]
  [jdk.internal.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
  [java.lang.reflect.Method invoke Method.java 564]
  [org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint lambda$null$0 GenericEndpoint.java 65]
  [org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint request GenericEndpoint.java 120]
  [org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleRequest RemoteEndpoint.java 261]
  [org.eclipse.lsp4j.jsonrpc.RemoteEndpoint consume RemoteEndpoint.java 190]
  [org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer handleMessage StreamMessageProducer.java 194]
  [org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer listen StreamMessageProducer.java 94]
  [org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor run ConcurrentMessageProcessor.java 113]
  [java.util.concurrent.Executors$RunnableAdapter call Executors.java 515]
  [java.util.concurrent.FutureTask run FutureTask.java 264]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1130]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 630]
  [java.lang.Thread run Thread.java 832]]}
```

**Comment by bpringe** [comment]
Ok, so this didn't happen with another project I tried. It happens every time though with this project: https://github.com/eu400000/Calva-VSC-Outline-Issue. I have no clue what could be causing that, yet.

**Comment by bpringe** [comment]
Got the same error on another project, which I think was created with the shadow-cljs lein template, so it's not particular to that one project, though that can be a good test project to debug this.

**Comment by bpringe** [comment]
CC @borkdude. Just in case he sees something obvious 😄.

**Comment by ericdallo** [comment]
Oh, really weird indeed, @bpringe the best we can do is know what is the path clj-kondo is scanning, I'd suggest adding a `(log/info paths (string/join (System/getProperty "path.separator") paths))` here: https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/crawler.clj#L93
And check what we sent to clj-kondo before the exception

**Comment by bpringe** [comment]
So this is what I see right before the error.

```
2021/01/26 17:03:54 6068 INFO  clojure-lsp.crawler Analyzing 11 paths with clj-kondo with batch size of  1 ...
2021/01/26 17:03:54 6068 INFO  clojure-lsp.crawler paths=>>>>>> CLASSPATH=C:\Users\brand\.lein\self-installs\leiningen-2.9.5-standalone.jar
Applying task classpath to []
C:\Users\brand\Downloads\test\test\test;C:\Users\brand\Downloads\test\test\src;C:\Users\brand\Downloads\test\test\dev-resources;C:\Users\brand\Downloads\test\test\resources;C:\Users\brand\Downloads\test\test\target\default\classes;C:\Users\brand\.m2\repository\org\clojure\clojure\1.10.1\clojure-1.10.1.jar;C:\Users\brand\.m2\repository\org\clojure\spec.alpha\0.2.176\spec.alpha-0.2.176.jar;C:\Users\brand\.m2\repository\org\clojure\core.specs.alpha\0.2.44\core.specs.alpha-0.2.44.jar;C:\Users\brand\.m2\repository\testlib\testlib\0.1.0\testlib-0.1.0.jar;C:\Users\brand\.m2\repository\nrepl\nrepl\0.8.3\nrepl-0.8.3.jar;C:\Users\brand\.m2\repository\clojure-complete\clojure-complete\0.2.5\clojure-complete-0.2.5.jar
2021/01/26 17:03:54 6068 ERROR clojure-lsp.main #error {
 :cause The filename, directory name, or volume label syntax is incorrect
 :via
 [{:type java.io.IOException
   :message The filename, directory name, or volume label syntax is incorrect
   :at [java.io.WinNTFileSystem canonicalize0 WinNTFileSystem.java -2]}]
```

The code I used was like this:

```clojure
(defn ^:private run-kondo-on-paths! [paths]
  (let [lint-paths (string/join (System/getProperty "path.separator") paths)]
    (log/info "paths=>>>>>>" lint-paths)
    (kondo/run! (kondo-args {:parallel true
                             :lint [lint-paths]} false))))
```

**Comment by bpringe** [comment]
Judging by

>2021/01/26 17:03:54 6068 INFO  clojure-lsp.crawler paths=>>>>>> CLASSPATH=C:\Users\brand\.lein\self-installs\leiningen-2.9.5-standalone.jar

and

> The filename, directory name, or volume label syntax is incorrect

maybe the `CLASSPATH=` at the beginning of that is part of the issue? I'm guessing that should just be a valid path. Not sure how `CLASSPATH=` made it into there, but maybe something went wrong with an earlier split.

**Comment by ericdallo** [comment]
yeah, that shouldn't be there hahah, not sure what added that 🤔

**Comment by ericdallo** [comment]
oh, probably is the return of the classpath-cmd from that project-spec

**Comment by ericdallo** [comment]
What kind of project is it? execute on of these  your project and check the result: https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/crawler.clj#L51-L59

**Comment by bpringe** [comment]
So in this lein project for which I get the error, I ran `lein classpath` in the terminal and got this:

```
PS C:\Users\brand\Downloads\test\test> lein classpath
CLASSPATH=C:\Users\brand\.lein\self-installs\leiningen-2.9.5-standalone.jar
Applying task classpath to []
C:\Users\brand\Downloads\test\test\test;C:\Users\brand\Downloads\test\test\src;C:\Users\brand\Downloads\test\test\dev-resources;C:\Users\brand\Downloads\test\test\resources;C:\Users\brand\Downloads\test\test\target\default\classes;C:\Users\brand\.m2\repository\org\clojure\clojure\1.10.1\clojure-1.10.1.jar;C:\Users\brand\.m2\repository\org\clojure\spec.alpha\0.2.176\spec.alpha-0.2.176.jar;C:\Users\brand\.m2\repository\org\clojure\core.specs.alpha\0.2.44\core.specs.alpha-0.2.44.jar;C:\Users\brand\.m2\repository\testlib\testlib\0.1.0\testlib-0.1.0.jar;C:\Users\brand\.m2\repository\nrepl\nrepl\0.8.3\nrepl-0.8.3.jar;C:\Users\brand\.m2\repository\clojure-complete\clojure-complete\0.2.5\clojure-complete-0.2.5.jar
```

That's really weird... I haven not seen those first two lines of output before.

**Comment by ericdallo** [comment]
yeah, what's your lein version?

**Comment by bpringe** [comment]
`Leiningen 2.9.5 on Java 15.0.1 OpenJDK 64-Bit Server VM`

**Comment by bpringe** [comment]
When I run this in another project though, I don't see those two first lines... 🤔

**Comment by bpringe** [comment]
Ok now it's working in projects it didn't work in before.... and the `lein classpath` command is giving normal output again... Wonder if this is something strange with my VM.

**Comment by ericdallo** [comment]
really crazy hahah

**Comment by bpringe** [comment]
Latest version works fine too.... (made sure since I had modified the jar for logging.) This is really crazy. It's time for me to stop for the day, haha. I'll close this for now, and try to test the Windows related issues for #261 again tomorrow.
