### ISSUE TITLE
server is crushing

### ISSUE THREAD

**Issue by barkanido** [clojure-lsp/clojure-lsp#660]
**Describe the bug**
getting this error while attaching a vim buffer using [lsp-config](https://github.com/neovim/nvim-lspconfig) 
```
Dec 07, 2021 1:27:07 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: An error occurred while processing an incoming message.
java.lang.NullPointerException
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```
I am not sure if this is the lsp server-side or the client-side, to be honest. but since other lsp server are able to attach, I think clojure_lsp crushes.

**To Reproduce**
this is an internal project and the lep server is started with no args

**User details (please complete the following information):**
 - OS: Ubuntu
 - Version: clojure-lsp 2021.12.01-12.28.16
clj-kondo 2021.10.20-SNAPSHOT

**Comment by barkanido** [comment]
from the client debug log, you can maybe see the last message sent to the server:
```
[INFO][2021-12-07 13:44:31] .../vim/lsp/rpc.lua:316	"Starting RPC client"	{  args = {},  cmd = "clojure-lsp",  extra = {    cwd = "/home/ido-barkan/code/work/af-loyals"  }}
[DEBUG][2021-12-07 13:44:31] .../vim/lsp/rpc.lua:395	"rpc.send"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false,        <metatable> = <1>{          __tostring = <function 1>        }      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },              <metatable> = <table 1>            },            <metatable> = <table 1>          },          dynamicRegistration = false,          <metatable> = <table 1>        },        completion = {          completionItem = {            commitCharactersSupport = true,            deprecatedSupport = true,            documentationFormat = { "markdown", "plaintext" },            insertReplaceSupport = true,            labelDetailsSupport = true,            preselectSupport = true,            resolveSupport = {              properties = { "documentation", "detail", "additionalTextEdits" },              <metatable> = <table 1>            },            snippetSupport = true,            tagSupport = {              valueSet = { 1 },              <metatable> = <table 1>            },            <metatable> = <table 1>          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },            <metatable> = <table 1>          },          contextSupport = false,          dynamicRegistration = false,          <metatable> = <table 1>        },        declaration = {          linkSupport = true,          <metatable> = <table 1>        },        definition = {          linkSupport = true,          <metatable> = <table 1>        },        documentHighlight = {          dynamicRegistration = false,          <metatable> = <table 1>        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false,          <metatable> = <table 1>        },        implementation = {          linkSupport = true,          <metatable> = <table 1>        },        publishDiagnostics = {          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        references = {          dynamicRegistration = false,          <metatable> = <table 1>        },        rename = {          dynamicRegistration = false,          prepareSupport = true,          <metatable> = <table 1>        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            documentationFormat = { "markdown", "plaintext" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false,          <metatable> = <table 1>        },        typeDefinition = {          linkSupport = true,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      window = {        showDocument = {          support = false,          <metatable> = <table 1>        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false,            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workDoneProgress = true,        <metatable> = <table 1>      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" },          <metatable> = <table 1>        },        workspaceFolders = true,        <metatable> = <table 1>      },      <metatable> = <table 1>    },    clientInfo = {      name = "Neovim",      version = "0.5.1"    },    initializationOptions = vim.empty_dict(),    processId = 3984653,    rootPath = "/home/ido-barkan/code/work/af-loyals",    rootUri = "file:///home/ido-barkan/code/work/af-loyals",    trace = "off",    workspaceFolders = { {        name = "/home/ido-barkan/code/work/af-loyals",        uri = "file:///home/ido-barkan/code/work/af-loyals"      } }  }}
[DEBUG][2021-12-07 13:44:31] .../vim/lsp/rpc.lua:496	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "clojure-lsp",    value = {      kind = "begin",      percentage = 0,      title = "clojure-lsp"    }  }}
```

**Comment by ericdallo** [comment]
thanks, I'll take a look

**Comment by ericdallo** [comment]
@barkanido I can't easily test the sent initialize info, could you send the json version of that? since it's part of the protocol there must be a way to get that as json, I also didn't find anything to convert that to json

**Comment by barkanido** [comment]
after trying to indent this it seems like a giant Lua dictionary (the LSP client in neovim is written in Lua I think).
It does state the protocol method and its parameters so it might help.

```lua
{  id = 1,  
   jsonrpc = "2.0",  
   method = "initialize",  
   params = {    
        capabilities = {      
            callHierarchy = {        
                dynamicRegistration = false,        
                <metatable> = <1>{__tostring = <function 1>}
            },      
            textDocument = {        
                codeAction = {          
                    codeActionLiteralSupport = {            
                        codeActionKind = {              
                            valueSet = { "", "Empty", "QuickFix", 
                                         "Refactor", "RefactorExtract", 
                                         "RefactorInline", "RefactorRewrite", 
                                         "Source", "SourceOrganizeImports", 
                                         "quickfix", "refactor", "refactor.extract", 
                                         "refactor.inline", "refactor.rewrite", 
                                         "source", "source.organizeImports" },
                            <metatable> = <table 1>            
                            },            
                        <metatable> = <table 1>          
                        },          
                    dynamicRegistration = false,
                    <metatable> = <table 1>
                    },        
            completion = {          
                completionItem = {            
                    commitCharactersSupport = true,            
                    deprecatedSupport = true,            
                    documentationFormat = { "markdown", "plaintext" },            
                    insertReplaceSupport = true,                
                    labelDetailsSupport = true,            
                    preselectSupport = true,            
                    resolveSupport = {              
                        properties = { "documentation", "detail", "additionalTextEdits" },
                        <metatable> = <table 1>     
                        },            
                    snippetSupport = true, 
                    tagSupport = {   
                        valueSet = { 1 },  
                        <metatable> = <table 1>
                        },            
                    <metatable> = <table 1>          
                    },
            completionItemKind = { 
            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },
            <metatable> = <table 1>
            },
        contextSupport = false,          
        dynamicRegistration = false,
        <metatable> = <table 1>        
        },
    declaration = {
        linkSupport = true,          
        <metatable> = <table 1>        
        },        
    definition = {          
        linkSupport = true,          
        <metatable> = <table 1>        
        },        
    documentHighlight = {          
        dynamicRegistration = false,          
        <metatable> = <table 1>        
        },        
    documentSymbol = {          
        dynamicRegistration = false,          
        hierarchicalDocumentSymbolSupport = true,          
        symbolKind = {            
            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },
            <metatable> = <table 1>
            },          
        <metatable> = <table 1>
        },
    hover = {
        contentFormat = { "markdown", "plaintext" },          
        dynamicRegistration = false,          
        <metatable> = <table 1>        
        },        
    implementation = {          
        linkSupport = true,
        <metatable> = <table 1>        
        },
    publishDiagnostics = {          
        relatedInformation = true,
        tagSupport = {            
            valueSet = { 1, 2 },            
            <metatable> = <table 1>          
            },          
        <metatable> = <table 1>        
        },        
        references = {          
            dynamicRegistration = false,          
            <metatable> = <table 1> 
            },        
        rename = {          
            dynamicRegistration = false,          
            prepareSupport = true,          
            <metatable> = <table 1>        
            },        
        signatureHelp = {
            dynamicRegistration = false,
            signatureInformation = {            
            documentationFormat = { "markdown", "plaintext" },            
            <metatable> = <table 1>          
            },          
        <metatable> = <table 1>        
        },
    synchronization = {          
        didSave = true,
        dynamicRegistration = false,          
        willSave = false,          
        willSaveWaitUntil = false,          
        <metatable> = <table 1>        
        },        
    typeDefinition = {          
        linkSupport = true,          
        <metatable> = <table 1>
        },        
    <metatable> = <table 1>
    },      
window = {        
    showDocument = {          
    support = false,          
    <metatable> = <table 1>        
    },        
showMessage = {          
    messageActionItem = {            
        additionalPropertiesSupport = false,            
        <metatable> = <table 1>          
        },          
    <metatable> = <table 1>        
    },        
workDoneProgress = true,        
<metatable> = <table 1>      
},      
workspace = {        
    applyEdit = true,        
    configuration = true,        
    symbol = {          
        dynamicRegistration = false,          
        hierarchicalWorkspaceSymbolSupport = true,          
        symbolKind = {            
            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },
            <metatable> = <table 1>          
            },
        <metatable> = <table 1>     
    },        
    workspaceEdit = {          
        resourceOperations = { "rename", "create", "delete" },          
        <metatable> = <table 1>        
        },        
    workspaceFolders = true,
    <metatable> = <table 1>      
    },      
<metatable> = <table 1>    
},    
clientInfo = {      
    name = "Neovim",      
    version = "0.5.1"    
    },    
    initializationOptions = vim.empty_dict(),    
    processId = 3984653,    
    rootPath = "/home/ido-barkan/code/work/af-loyals",    
    rootUri = "file:///home/ido-barkan/code/work/af-loyals",    
    trace = "off",    
    workspaceFolders = { {        
        name = "/home/ido-barkan/code/work/af-loyals",        
        uri = "file:///home/ido-barkan/code/work/af-loyals"      
} }  }}
```

**Comment by ericdallo** [comment]
This is not a valid json yet :/
Is there any way to concert that to a valid json or get the json from nvim easily?
