### ISSUE TITLE
Format command fails with java.lang.RuntimeException

### ISSUE THREAD

**Issue by maksimr** [clojure-lsp/clojure-lsp#881]
**Describe the bug**
Format command fails with java.lang.RuntimeException

```
Caused by: java.lang.RuntimeException: No dispatch macro for: "
        at clojure.lang.Util.runtimeException(Util.java:221)
```

The problem in [:indents and :test-code properties](https://github.com/maksimr/playground-cljs/blob/master/.cljfmt.edn#L5-L10) inside **.cljfmt.end** config

**To Reproduce**

1. Clone project https://github.com/maksimr/playground-cljs
2. Run `clojure-lsp format`
3. See error

**Expected behavior**
No exception

<details>
 <summary><b>clojure-lsp output</b></summary>
<pre>
[100%] Project analyzed
Formatting namespaces...
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.RuntimeException: No dispatch macro for: "
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at clojure.core$deref_future.invokeStatic(core.clj:2317)
        at clojure.core$future_call$reify__8544.deref(core.clj:7041)
        at clojure.core$deref.invokeStatic(core.clj:2337)
        at clojure.core$deref.invoke(core.clj:2323)
        at clojure.core$map$fn__5935.invoke(core.clj:2772)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:58)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at clojure_lsp.internal_api$format_BANG__STAR_.invokeStatic(internal_api.clj:353)
        at clojure_lsp.internal_api$format_BANG__STAR_.invoke(internal_api.clj:341)
        at clojure_lsp.internal_api$format_BANG_.invokeStatic(internal_api.clj:413)
        at clojure_lsp.internal_api$format_BANG_.invoke(internal_api.clj:412)
        at clojure_lsp.main$handle_action_BANG_.invokeStatic(main.clj:147)
        at clojure_lsp.main$handle_action_BANG_.invoke(main.clj:136)
        at clojure_lsp.main$run_BANG_.invokeStatic(main.clj:162)
        at clojure_lsp.main$run_BANG_.doInvoke(main.clj:155)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at clojure_lsp.main$_main.invokeStatic(main.clj:165)
        at clojure_lsp.main$_main.doInvoke(main.clj:164)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure_lsp.main.main(Unknown Source)
Caused by: java.lang.RuntimeException: No dispatch macro for: "
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:552)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
        at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
        at clojure.lang.EdnReader.read(EdnReader.java:145)
        at clojure.lang.EdnReader$MetaReader.invoke(EdnReader.java:576)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
        at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
        at clojure.lang.EdnReader.read(EdnReader.java:145)
        at clojure.lang.EdnReader.read(EdnReader.java:111)
        at clojure.lang.EdnReader.readString(EdnReader.java:67)
        at clojure.edn$read_string.invokeStatic(edn.clj:46)
        at clojure.edn$read_string.invoke(edn.clj:37)
        at clojure_lsp.feature.format$resolve_user_cljfmt_config.invokeStatic(format.clj:31)
        at clojure_lsp.feature.format$resolve_user_cljfmt_config.invoke(format.clj:19)
        at clojure_lsp.feature.format$resolve_cljfmt_config.invokeStatic(format.clj:35)
        at clojure_lsp.feature.format$resolve_cljfmt_config.invoke(format.clj:33)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at clojure.core.memoize$through_STAR_$fn__3932.invoke(memoize.clj:107)
        at clojure.core.cache$through$fn__3668.invoke(cache.clj:55)
        at clojure.core.memoize$through_STAR_$fn__3928$fn__3929.invoke(memoize.clj:106)
        at clojure.core.memoize.RetryingDelay.deref(memoize.clj:47)
        at clojure.core$deref.invokeStatic(core.clj:2337)
        at clojure.core$deref.invoke(core.clj:2323)
        at clojure.core.memoize$cached_function$fn__3996.doInvoke(memoize.clj:231)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure_lsp.feature.format$formatting.invokeStatic(format.clj:44)
        at clojure_lsp.feature.format$formatting.invoke(format.clj:42)
        at clojure_lsp.handlers$formatting.invokeStatic(handlers.clj:268)
        at clojure_lsp.handlers$formatting.invoke(handlers.clj:267)
        at clojure_lsp.internal_api$format_BANG__STAR_$fn__38165.invoke(internal_api.clj:351)
        at clojure.core$pmap$fn__8552$fn__8553.invoke(core.clj:7089)
        at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
</pre>
</details>

**User details:**
 - OS: MacOS
 - Version: 
clojure-lsp 2022.03.26-18.47.08 
clj-kondo 2022.03.10-SNAPSHOT

**Comment by ericdallo** [comment]
Thanks for the report
@snoe is this related with recent changes to cljfmt parsing? any thoughts?

**Comment by ericdallo** [comment]
@maksimr I think you should use `#re` not `#` as it's not supported by edn?

**Comment by ericdallo** [comment]
Closing this as edn doesn't support `#`, you should use `#re`

**Comment by maksimr** [comment]
@ericdallo thanks, I'll try to replace `#` but `:test-code` property doesn't work either.

I have taken this from [Calva documentation](https://calva.io/formatting/). And what is interesting it works in VS Code and as I undestand Calva use clojure-lsp

**Comment by ericdallo** [comment]
@maksimr that happens because you can't use `#()` only `(fn [])`, otherwise parsing edn will try to handle `#(` as a reader macro

**Comment by ericdallo** [comment]
Not sure if cljfmt understands that or handle that file differently

**Comment by maksimr** [comment]
@ericdallo thanks, yup, I have just read about purpose of [`#` dispatch symbol](https://github.com/edn-format/edn#-dispatch-character) in edn. Looks like cljfmt already has issue request about it https://github.com/weavejester/cljfmt/issues/244
